# 10.14 required for some C++17 features used in TBB
c_stdlib_version:          # [osx and x86_64]
  - 10.14                  # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - 10.14                  # [osx and x86_64]

