{% set name = "freud" %}
{% set version = "1.0.0" %}
{% set sha256 = "71599d85be07e6ed9afc3c85ec9a5ab5eafa8c8185fd4b306eb4ae43d5e127f2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://glotzerlab.engin.umich.edu/Downloads/{{ name }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --ignore-installed --no-cache-dir -vvv"
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - cython
    - tbb
    - tbb-devel
    - numpy =1.11

  run:
    - python
    - tbb
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  imports:
    - freud

about:
  home: https://github.com/glotzerlab/{{ name }}
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The freud library provides users the ability to analyze generic data from a variety of sources including simulation and experimental data for advanced metrics such as the radial distribution function and various order parameters.'
  doc_url: http://{{ name }}.readthedocs.io/
  dev_url: https://github.com/glotzerlab/{{ name }}

extra:
  recipe-maintainers:
    - bdice
    - vyasr
    - joaander
