{% set name = "freud" %}
{% set version = "0.10.0" %}
{% set sha256 = "f0d00cf5d958b0e3b819ab09ba0433f2fb29b0cdac30879222d49cad7e460e1f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://glotzerlab.engin.umich.edu/Downloads/{{ name }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - cython
    - tbb
    - numpy

  run:
    - python
    - tbb
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  imports:
    - freud

about:
  home: https://bitbucket.org/glotzer/{{ name }}
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The freud library provides users the ability to analyze generic data from a variety of sources including simulation and experimental data for advanced metrics such as the radial distribution function and various order parameters.'
  doc_url: http://{{ name }}.readthedocs.io/
  dev_url: https://bitbucket.org/glotzer/{{ name }}

extra:
  recipe-maintainers:
    - bdice
    - vyasr
    - joaander
