{% set name = "freud" %}
{% set version = "0.9.0" %}
{% set sha256 = "d51ac395f4e497bdc9761af26ad1a9c2b9cb6a29e644e9adaa04f0913a7979d0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://glotzerlab.engin.umich.edu/Downloads/{{ name }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

  host:
    - python
    - cython
    - tbb
    - boost
    - numpy

  run:
    - python
    - tbb
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  imports:
    - freud

about:
  home: https://bitbucket.org/glotzer/{{ name }}
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The freud library provides users the ability to analyze generic data from a variety of sources including simulation and experimental data for advanced metrics such as the radial distribution function and various order parameters.'
  doc_url: http://{{ name }}.readthedocs.io/
  dev_url: https://bitbucket.org/glotzer/{{ name }}

extra:
  recipe-maintainers:
    - bdice
    - vyasr
    - joaander
